### ISSUE TITLE
Log History dialog shows last column "Description" too small

### ISSUE THREAD

**Issue by davidcallen** [RapidSVN/RapidSVN#14]
The Log History dialog shows a listview of revisions.  The last column in this listview is "Description". It appears rather narrow, and does not size to fill the remaining space in the ListView.  

Therefore have to keep resizing it on every display of this window, which is a bit tedious.

**Comment by davidcallen** [comment]
Attached a fix for this.  It essentially a simple fix to resize the last column (to fill space) as the ListView resizes.  However I had to reorganize the log_rev_list.hpp and add a log_rev_list.cpp so that I could add an BEGIN_EVENT_TABLE so I could override the onSize() event. This makes the change look more complicated than it really is.
[git-diff-issue-14-log-history-dialog-last-column-autosize.txt](https://github.com/RapidSVN/RapidSVN/files/555275/git-diff-issue-14-log-history-dialog-last-column-autosize.txt)

**Comment by XelaRellum** [comment]
Hellow David, can you create a pull request for this (and the other outstanding patches)?

**Comment by davidcallen** [comment]
Thanks Alex for merging my patches. I am new to git, but I suppose if I use pull requests it will make this process easier. I will read more on git, and the best way to do this, and get back to you.

**Comment by davidcallen** [comment]
I have created a Pull Request for this issue (and the other outstanding patches). Thanks.
