### ISSUE TITLE
Log dialog does not have sortable columns in the affectedfiles listview

### ISSUE THREAD

**Issue by davidcallen** [RapidSVN/RapidSVN#24]
It would be very useful to be able to sort the file list by clicking on the column headers in this dialog.

**Comment by davidcallen** [comment]
Submitted Pull Request for the fix.

**Comment by davidcallen** [comment]
If you need me to re-work any aspect of this Pull request (so it can be merged into the codebase) just let me know, thanks.

**Comment by XelaRellum** [comment]
I think I have merged this pull request last year? I just checked the closed pull requests. Do you find something missing?

**Comment by davidcallen** [comment]
No sorry, my fault. I accidentally used an old copy of master branch and didnt see my code changes, and with the issue still open i assumed it hadnt merged. I'll close this issue.
