### ISSUE TITLE
License libsvncpp

### ISSUE THREAD

**Issue by richdev123** [RapidSVN/RapidSVN#32]
Hi All,

I would like to use parts of libsvncpp in a closed source project. my project uses it to fetch data from a backend and does not show SVN related thing to the end user, so it will never be competing. but since I can't make it completely open source I would like to know if i can legally use the SVN library for communicating with a SVN server?

Is the entire repository GPL or is the libsvncpp already LGPL? (if http://rapidsvn.tigris.org/ds/viewMessage.do?dsForumId=671&dsMessageId=550450 is correct that would still be the case)

You did a great job abstracting the APR logic and the like and it would be a trouble for me if I would have to reinvent the wheel instead of joining because of licensing. (btw is there any change of merging/moving libsvncpp to the apache codebase?)

Kind regards,
Rich

**Comment by richdev123** [comment]
Sounds good, please let me know if there is anything I can do

2018-01-30 17:53 GMT+01:00 Alexander Mueller <notifications@github.com>:

**Comment by richdev123** [comment]
Is there any news on this yet? positive or negative?

**Comment by XelaRellum** [comment]
I have received no response from the mailinglist. So I will move forward in changing the license to LGPLv3. Give me some days until I find the time...

**Comment by XelaRellum** [comment]
The license for `libsvncpp` was changed to LGPLv3. Closing this issue...

**Comment by richdev123** [comment]
Thanks :-)

2018-03-19 22:57 GMT+01:00 Alexander Mueller <notifications@github.com>:
