### ISSUE TITLE
SVN Client Too Old

### ISSUE THREAD

**Issue by garethflowers** [RapidSVN/RapidSVN#4]
I'm currently getting an error when trying to work with a repository created using another SVN client.

    Error: Error while updating filelist (This client is too old to work with the
    working copy at 'C:\TestSVNRepo' (format 31).
    You need to get a newer Subversion client. For more details, see
      http://subversion.apache.org/faq.html#working-copy-format-change
    )

Is there a solution/workaround to this??

**Comment by XelaRellum** [comment]
A workaround on Windows is to replace the linsvn*.dlls with the ones from the subversion command line client. 

Let me know if this works for you.

**Comment by garethflowers** [comment]
Switching out the DLL's worked! Thanks.

**Comment by marcominetti** [comment]
Where I can get the subversion command line client you mentioned? I have tortoisesvn but no dll with matching names are available...

**Comment by marcominetti** [comment]
Ok, got it at http://sourceforge.net/projects/win32svn/
